<?php

/**
 * $Id: xoops_version.php,v 1.5 2005/06/13 18:23:20 fx2024 Exp $
 * Module: SmartMedia
 * Author: The SmartFactory <www.smartfactory.ca>
 * Licence: GNU
 */

$modversion['name'] = _MI_SMEDIA_MD_NAME;
$modversion['version'] = 0.85;
$modversion['description'] = _MI_SMEDIA_MD_DESC;
$modversion['author'] = "The SmartFactory [www.smartfactory.ca]";
$modversion['credits'] = "Innu Aitun, Radio-Canada, InBox Solutions, Nelson Dumais, Christian Aubry, fx2024, RISQ";
$modversion['help'] = "";
$modversion['license'] = "GNU General Public License (GPL)";
$modversion['official'] = 0;
$modversion['image'] = "images/smartmedia_logo.png";
$modversion['dirname'] = "smartmedia";

// Added by marcan for the About page in admin section
$modversion['adminMenu'] = "smartmedia_adminMenu";
$modversion['modFooter'] = "smartmedia_modFooter";
$modversion['developer_lead'] = "marcan [Marc-André Lanciault]";
$modversion['developer_contributor'] = "Innu Aitun, Radio-Canada, InBox Solutions, Nelson Dumais, Christian Aubry, fx2024, RISQ";
$modversion['developer_website_url'] = "http://dev.xoops.org/modules/xfmod/project/?group_id=1219";
$modversion['developer_website_name'] = "SmartMedia at the Developers Forge";
$modversion['developer_email'] = "marcan@smartfactory";
$modversion['status_version'] = "Beta 1";
$modversion['status'] = "Beta";
$modversion['date'] = "2005-06-14";

$modversion['warning'] = _MI_SMEDIA_WARNING_BETA;

$modversion['demo_site_url'] = "http://demo.smartfactory.ca/modules/smartmedia/";
$modversion['demo_site_name'] = _MI_SMEDIA_DEMO_SITE;
$modversion['support_site_url'] = "http://www.smartfactory.ca";
$modversion['support_site_name'] = "SmartFactory.ca";
$modversion['submit_bug'] = "http://dev.xoops.org/modules/xfmod/tracker/?func=add&group_id=1219&atid=1051";
$modversion['submit_feature'] = "http://dev.xoops.org/modules/xfmod/tracker/?func=add&group_id=1219&atid=1054";

$modversion['author_word'] = "This module was made possible by the financial support of the <b>Innus Nation</b> (<a href='http://www.innuaitun.com'>www.innuaitun.com</a>) and Montreal's web developing firm <b>InBox Solutions</b> (<a href='http://www.inboxsolutions.net'>www.inboxsolutions.net</a>).<br />
<br />
The SmartFactory would like to thank La Société Radio-Canada for theire help with the database structure and the DHTML tabs on the user side. Radio-Canada allowed us to inspired ourself from their excellent <a href='http://archives.radio-canada.ca/'>Archive Section</a>.<br />
<br />
We would also like to thank Nelson Dumais, leader of the InnuAitun project and Christian Aubry, <a href='http://www.risq.qc.ca/'>RISQ</a>'s coordonator for the InnuAitun project.";

$modversion['version_history'] = "
=> Version 0.85 Beta (2005-06-14)<br />
====================================<br />

- Addition of a Clip Formats management functionality including support for all major multimedia format as well as the possibility to add, edit or delete any format<br />
- Addition of check database table functionnality, including  a new dbUpdater class that performs the db upgrade<br />
- Addition of a counter for clips and folders<br />
- Addidion of a recent clips block<br />
- The width and height of a clip can now be customize for each clip individually<br />
<br />

=> Version 0.75 Beta (2005-04-16)<br />
====================================<br />
<br />
- First Public release of the module<br />
";


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "smartmedia_categories";
$modversion['tables'][1] = "smartmedia_categories_text";
$modversion['tables'][2] = "smartmedia_clips";
$modversion['tables'][3] = "smartmedia_clips_text";
$modversion['tables'][4] = "smartmedia_folders";
$modversion['tables'][5] = "smartmedia_folders_categories";
$modversion['tables'][6] = "smartmedia_folders_text";
$modversion['tables'][7] = "smartmedia_formats";
$modversion['tables'][8] = "smartmedia_meta";
$modversion['tables'][9] = "smartmedia_status";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "smartmedia_search";
// Menu
$modversion['hasMain'] = 1;

$modversion['blocks'][1]['file'] = "clips_recent.php";
$modversion['blocks'][1]['name'] = _MI_SMEDIA_BLOCK_CLIPS_RECENT;
$modversion['blocks'][1]['description'] = _MI_SMEDIA_BLOCK_CLIPS_RECENT_DSC;
$modversion['blocks'][1]['show_func'] = "b_smartmedia_clips_recent_show";
$modversion['blocks'][1]['edit_func'] = "b_smartmedia_clips_recent_edit";
$modversion['blocks'][1]['options'] = "20|5";
$modversion['blocks'][1]['template'] = "smartmedia_clips_recent.html";

// Templates
$modversion['templates'][1]['file'] = 'smartmedia_header.html';
$modversion['templates'][1]['description'] = 'Module header';

$modversion['templates'][2]['file'] = 'smartmedia_footer.html';
$modversion['templates'][2]['description'] = 'Module footer';

$modversion['templates'][3]['file'] = 'smartmedia_index.html';
$modversion['templates'][3]['description'] = 'Display index';

$modversion['templates'][4]['file'] = 'smartmedia_category.html';
$modversion['templates'][4]['description'] = 'Display category';

$modversion['templates'][5]['file'] = 'smartmedia_folder.html';
$modversion['templates'][5]['description'] = 'Display folder';

$modversion['templates'][6]['file'] = 'smartmedia_wmp_video.html';
$modversion['templates'][6]['description'] = 'Display Windows Media Player Movie';

$modversion['templates'][7]['file'] = 'smartmedia_qt_video.html';
$modversion['templates'][7]['description'] = 'Display QuickTime Movie';

$modversion['templates'][8]['file'] = 'smartmedia_flash_video.html';
$modversion['templates'][8]['description'] = 'Display Flash';

$modversion['templates'][9]['file'] = 'smartmedia_wmp_audio.html';
$modversion['templates'][9]['description'] = 'Display Windows Media Player Audio';

$modversion['templates'][10]['file'] = 'smartmedia_real_audio.html';
$modversion['templates'][10]['description'] = 'Display Real Player Audio';

$modversion['templates'][11]['file'] = 'smartmedia_real_video.html';
$modversion['templates'][11]['description'] = 'Display Real Player Video';

$modversion['templates'][12]['file'] = 'smartmedia_qt_audiohtml';
$modversion['templates'][12]['description'] = 'Display QuickTime Audio';

$modversion['templates'][13]['file'] = 'smartmedia_clip.html';
$modversion['templates'][13]['description'] = 'Display clip';


// Config Settings (only for modules that need config settings generated automatically)

$modversion['config'][1]['name'] = 'index_msg';
$modversion['config'][1]['title'] = '_MI_SMEDIA_INDEX_MSG';
$modversion['config'][1]['description'] = '_MI_SMEDIA_INDEX_MSGDSC';
$modversion['config'][1]['formtype'] = 'textarea';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = '';

$modversion['config'][2]['name'] = 'categories_on_index';
$modversion['config'][2]['title'] = '_MI_SMEDIA_CAT_ON_INDEX';
$modversion['config'][2]['description'] = '_MI_SMEDIA_CAT_ON_INDEXDSC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 0;
$modversion['config'][2]['options'] = array(_MI_SMEDIA_ALL => 0, '4' => 4, '8' => 8, '12' => 12, '20' => 20, '30' => 30, '50' => 50);

$modversion['config'][3]['name'] = 'folders_per_category';
$modversion['config'][3]['title'] = '_MI_SMEDIA_FOL_PER_CAT';
$modversion['config'][3]['description'] = '_MI_SMEDIA_FOL_PER_CATDSC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;
$modversion['config'][3]['options'] = array(_MI_SMEDIA_ALL => 0, '4' => 4, '8' => 8, '12' => 12, '20' => 20, '30' => 30, '50' => 50);

$modversion['config'][4]['name'] = 'clips_per_folder';
$modversion['config'][4]['title'] = '_MI_SMEDIA_CLI_PER_FOL';
$modversion['config'][4]['description'] = '_MI_SMEDIA_CLI_PER_FOLDSC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;
$modversion['config'][4]['options'] = array(_MI_SMEDIA_ALL => 0,'4' => 4, '8' => 8, '12' => 12, '20' => 20, '30' => 30, '50' => 50);

$modversion['config'][5]['name'] = 'cat_per_page_admin';
$modversion['config'][5]['title'] = '_MI_SMEDIA_CAT_ON_ADMIN';
$modversion['config'][5]['description'] = '_MI_SMEDIA_CAT_ON_ADMINDSC';
$modversion['config'][5]['formtype'] = 'select';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 0;
$modversion['config'][5]['options'] = array(_MI_SMEDIA_ALL => 0, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);

$modversion['config'][6]['name'] = 'folder_per_page_admin';
$modversion['config'][6]['title'] = '_MI_SMEDIA_FOLDER_ON_ADMIN';
$modversion['config'][6]['description'] = '_MI_SMEDIA_FOLDER_ON_ADMINDSC';
$modversion['config'][6]['formtype'] = 'select';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;
$modversion['config'][6]['options'] = array(_MI_SMEDIA_ALL => 0, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);

$modversion['config'][7]['name'] = 'main_image_width';
$modversion['config'][7]['title'] = '_MI_SMEDIA_MAIN_IMG_WIDTH';
$modversion['config'][7]['description'] = '_MI_SMEDIA_MAIN_IMG_WIDTHDSC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = '300';

$modversion['config'][8]['name'] = 'list_image_width';
$modversion['config'][8]['title'] = '_MI_SMEDIA_LIST_IMG_WIDTH';
$modversion['config'][8]['description'] = '_MI_SMEDIA_LIST_IMG_WIDTHDSC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = '150';

$modversion['config'][9]['name'] = 'default_language';
$modversion['config'][9]['title'] = '_MI_SMEDIA_DEFAULT_LANGUAGE';
$modversion['config'][9]['description'] = '_MI_SMEDIA_DEFAULT_LANGUAGEDSC';
$modversion['config'][9]['formtype'] = 'select';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['default'] = 'english';
include_once XOOPS_ROOT_PATH . "/class/xoopslists.php";
$myList = new XoopsLists();
$modversion['config'][9]['options'] = $myList->getLangList();

$modversion['config'][10]['name'] = 'highlight_color';
$modversion['config'][10]['title'] = '_MI_SMEDIA_HIGHLIGHT_COLOR';
$modversion['config'][10]['description'] = '_MI_SMEDIA_HIGHLIGHT_COLORDSC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = '#FFFF80';

/*
 $modversion['config'][1]['name'] = 'itemtype';
 $modversion['config'][1]['title'] = '_MI_SMEDIA_ITEM_TYPE';
 $modversion['config'][1]['description'] = '_MI_SMEDIA_ITEM_TYPEDSC';
 $modversion['config'][1]['formtype'] = 'select';
 $modversion['config'][1]['valuetype'] = 'text';
 $modversion['config'][1]['default'] = 'article';
 $modversion['config'][1]['options'] = array('Item' => 'item', 'Article' => 'article', 'Project' => 'project');

 $modversion['config'][2]['name'] = 'allowsubmit';
 $modversion['config'][2]['title'] = '_MI_SMEDIA_ALLOWSUBMIT';
 $modversion['config'][2]['description'] = '_MI_SMEDIA_ALLOWSUBMITDSC';
 $modversion['config'][2]['formtype'] = 'yesno';
 $modversion['config'][2]['valuetype'] = 'int';
 $modversion['config'][2]['default'] = 0;

 $modversion['config'][5]['name'] = 'dateformat';
 $modversion['config'][5]['title'] = '_MI_SMEDIA_DATEFORMAT';
 $modversion['config'][5]['description'] = '_MI_SMEDIA_DATEFORMATDSC';
 $modversion['config'][5]['formtype'] = 'textbox';
 $modversion['config'][5]['valuetype'] = 'text';
 $modversion['config'][5]['default'] = 'd-M-Y H:i';
 */

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'itemid';
$modversion['comments']['pageName'] = 'item.php';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'smartmedia_com_approve';
$modversion['comments']['callback']['update'] = 'smartmedia_com_update';

// Notification
$modversion['hasNotification'] = 0;
//$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
//$modversion['notification']['lookup_func'] = 'smartmedia_notify_iteminfo';

?>