<?php
/************************************************************************/
/* Donations - Paypal financial management module for Xoops 2           */
/* Copyright (c) 2004 by Xoops2 Donations Module Dev Team			    */
/* http://dev.xoops.org/modules/xfmod/project/?group_id=1060			*/
/* $Id$      */
/************************************************************************/
/*                                                                      */
/* Based on NukeTreasury for PHP-Nuke - by Dave Lawrence AKA Thrash     */
/* NukeTreasury - Financial management for PHP-Nuke                     */
/* Copyright (c) 2004 by Dave Lawrence AKA Thrash                       */
/*                       thrash@fragnastika.com                         */
/*                       thrashn8r@hotmail.com                          */
/*                                                                      */
/************************************************************************/
/*                                                                      */
/* This program is free software; you can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/*                                                                      */
/* This program is distributed in the hope that it will be useful, but  */
/* WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU     */
/* General Public License for more details.                             */
/*                                                                      */
/* You should have received a copy of the GNU General Public License    */
/* along with this program; if not, write to the Free Software          */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  */
/* USA                                                                  */
/************************************************************************/

$xdonDir = basename ( dirname( __FILE__ ) );

$modversion['name'] = ucfirst($xdonDir);
$modversion['version'] = "1.97";
$modversion['description'] = _MI_DON_DESC;
$modversion['author'] = "Xoops2 Donations Module Dev Team, zyspec (owners@zyspec.com), Mamba";
$modversion['credits'] = "Based on NukeTreasury for PHP-Nuke.<br />Xoops2 port maintained by the Xoops2 Donations Module Dev Team.";
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/xdonations_slogo.png";
$modversion['dirname'] = $xdonDir;
$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date']     = '2011/08/15';
$modversion["module_website_url"] = "http://www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["release"] = "23-07-2009";
$modversion["module_status"] = "RC";
$modversion["author_website_url"] = "http://www.herve-thouzard.com/";
$modversion["author_website_name"] = "Dave Lawrence AKA Thrash";
$modversion['min_php']='5.2';
$modversion['min_xoops']="2.5";

// Run Script After Installation
$modversion['onInstall'] = "include/installscript.php";

// Run Script On Update
$modversion['onUpdate'] = "include/onupdate.php";

// Run Script On Module Removal
$modversion['onUninstall'] = "include/uninstallscript.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "donations_config";
$modversion['tables'][1] = "donations_financial";
$modversion['tables'][2] = "donations_transactions";
$modversion['tables'][3] = "donations_translog";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";
$modversion['system_menu'] = 1;

// Blocks
$modversion['blocks'][1]['file'] = "donat_o_meter.php";
$modversion['blocks'][1]['name'] = _MI_DON_BNAME1;
$modversion['blocks'][1]['description'] = _MI_DON_BNAME1_DESC;
$modversion['blocks'][1]['show_func'] = "b_donations_donatometer_show";
$modversion['blocks'][1]['options'] = "10|1|0|"._MI_DON_BUTTON_URL."|110|23";
$modversion['blocks'][1]['edit_func'] = "b_donations_donatometer_edit";
$modversion['blocks'][1]['template'] = 'donations_donatometer.html';

$modversion['blocks'][2]['file'] = "donate.php";
$modversion['blocks'][2]['name'] = _MI_DON_BNAME2;
$modversion['blocks'][2]['description'] = _MI_DON_BNAME2_DESC;
$modversion['blocks'][2]['show_func'] = "b_donations_donate_show";
$modversion['blocks'][2]['template'] = 'donations_donate.html';

$modversion['blocks'][3]['file'] = "donors.php";
$modversion['blocks'][3]['name'] = _MI_DON_BNAME3;
$modversion['blocks'][3]['description'] = _MI_DON_BNAME3_DESC;
$modversion['blocks'][3]['show_func'] = "b_donations_donors_show";
$modversion['blocks'][3]['options'] = "10|1|0";
$modversion['blocks'][3]['edit_func'] = "b_donations_donors_edit";
$modversion['blocks'][3]['template'] = 'donations_donors.html';

// Menu
$modversion['hasMain'] = 1;

global $xoopsUser, $xoopsDB, $xoopsModule, $xoopsModuleConfig;
$hModConfig =& xoops_gethandler('config');
$hModule =& xoops_gethandler('module');

if ( is_object($xoopsUser) && ( $xoopsUser->isAdmin() ) ) {
    $modversion['sub'][1]['name'] = _MI_DON_ADMIN;
    $modversion['sub'][1]['url'] = "admin/index.php";
}

// Templates
$modversion['templates'][1]['file'] = 'donations_main.html';
$modversion['templates'][1]['description'] = 'Donations Main Template';


?>
